<?php
/**
 * 2007-2016 PrestaShop
 *
 * Thirty Bees is an extension to the PrestaShop e-commerce software developed by PrestaShop SA
 * Copyright (C) 2017 Thirty Bees
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    Thirty Bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017 Thirty Bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark & property of PrestaShop SA
 *

/** @var AdminThirtyBeesMigrateController $this */
?>
<div id="activityLogBlock" class="panel col-lg-12" style="display:none">
    <div class="panel-heading"><?php echo $this->l('Activity Log'); ?></div>
    <p id="upgradeResultCheck"></p>
    <div id="upgradeResultToDoList" style="width:890px!important;"></div>
    <div id="currentlyProcessing" style="display:none;float:left">
        <h4 id="pleaseWait"><?php echo $this->l('Currently processing'); ?> <img class="pleaseWait" src="<?php echo __PS_BASE_URI__; ?>img/loader.gif"/></h4>
        <div id="infoStep" class="processing" ><?php echo $this->l('Analyzing the situation...'); ?></div>
    </div>
    <div id="errorDuringUpgrade" style="display:none;float:right">
        <h4><?php echo $this->l('Errors'); ?></h4>
        <div id="infoError" class="processing" ></div>
    </div>
    <div class="clear">&nbsp;</div>
    <div id="quickInfo" class="processing"></div>
</div>
