<?php
/**
 * 2007-2016 PrestaShop
 *
 * Thirty Bees is an extension to the PrestaShop e-commerce software developed by PrestaShop SA
 * Copyright (C) 2017 Thirty Bees
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    Thirty Bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017 Thirty Bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark & property of PrestaShop SA
 */

/** @var AdminThirtyBeesMigrateController $this */
$upgrader = \PsOneSixMigrator\Upgrader::getInstance();
?>
<div class="clearfix">
	<strong><?php echo $this->l('Selected channel'); ?>:</strong> <em><?php echo $upgrader->channel; ?></em><br />
	<strong><?php echo $this->l('Going to migrate to thirty bees version'); ?>:</strong> <em><?php echo $upgrader->version ?: $this->l('Nothing available'); ?></em>
</div>
<form name="channelSelect" class="margin-form" action="<?php echo static::$currentIndex.'&token='.$this->token; ?>" method="post">
	<label for="channelSelect"><?php echo $this->l('Channel:'); ?></label>
	<select id="channelSelect" name="channel">
        <?php foreach (['stable', 'rc', 'beta', 'alpha'] as $channel) : ?>
		<option id="use<?php echo ucfirst($channel); ?>" value="<?php echo $channel; ?>"<?php echo ($channel === $upgrader->channel) ? 'class="current" selected="selected">'.$channel.'*' : '>'.$channel ?></option>
        <?php endforeach; ?>
	</select>
	<div class="margin-form" style="">
		<button type="submit" class="btn btn-default"><i class="icon icon-save"></i> <?php echo $this->l('Save'); ?></button>
	</div>
	<p style="clear:both">Unless you are using a dedicated server, select "Low".<br>A high value can cause the upgrade to fail if your server is not powerful enough to process the upgrade tasks in a short amount of time.</p>
</form>

<div id="configResult">&nbsp;</div>
