<?php
/**
 * 2007-2016 PrestaShop
 *
 * Thirty Bees is an extension to the PrestaShop e-commerce software developed by PrestaShop SA
 * Copyright (C) 2017 Thirty Bees
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    Thirty Bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017 Thirty Bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark & property of PrestaShop SA
 */

/** @var AdminThirtyBeesMigrateController $this */
?>

<?php echo $this->displayBlockActivityLog(); ?>

<form action="<?php echo AdminThirtyBeesMigrateController::$currentIndex; ?>&amp;customSubmitAutoUpgrade=1&amp;token=<?php echo $this->token; ?>" method="post" enctype="multipart/form-data">
    <?php echo $this->displayConfigForm('upgradeOptions', $this->upgradeOptions, $this->l('Upgrade Options'), '', 'icon icon-wrench'); ?>
    <?php echo $this->displayConfigForm('backupOptions', $this->backupOptions, $this->l('Backup Options'), '', 'icon icon-server'); ?>
</form>


