<?php
/**
 * 2007-2016 PrestaShop
 *
 * Thirty Bees is an extension to the PrestaShop e-commerce software developed by PrestaShop SA
 * Copyright (C) 2017 Thirty Bees
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    Thirty Bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017 Thirty Bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark & property of PrestaShop SA
 */

/** @var AdminThirtyBeesMigrateController $this */
?>
<div id="channel-infos">
    <div class="all-infos">
        <?php if (isset($upgradeInfo['version_name'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('Name:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <span class="name"><?php echo $upgradeInfo['version_name']; ?>&nbsp;</span>
                </div>
            </div>
        <?php endif; ?>
        <?php if (isset($upgradeInfo['version_number'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('Version number:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <span class="version"><?php echo $upgradeInfo['version_num']; ?>&nbsp;</span>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!empty($upgradeInfo['link'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('URL:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <a class="url" href="<?php echo $upgradeInfo['link']; ?>"><?php echo $upgradeInfo['link']; ?></a>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!empty($upgradeInfo['md5'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('MD5 hash:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <span class="md5"><?php echo $upgradeInfo['md5']; ?>&nbsp;</span>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!empty($upgradeInfo['changelog'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('Changelog:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <a class="changelog" href="<?php echo $upgradeInfo['changelog']; ?>"><?php echo $this->l('see changelog'); ?></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
