<?php /** @var AdminThirtyBeesMigrate $this */ ?>
<div id="channel-infos">
    <div class="all-infos">
        <?php if (isset($upgradeInfo['version_name'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('Name:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <span class="name"><?php echo $upgradeInfo['version_name']; ?>&nbsp;</span>
                </div>
            </div>
        <?php endif; ?>
        <?php if (isset($upgradeInfo['version_number'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('Version number:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <span class="version"><?php echo $upgradeInfo['version_num']; ?>&nbsp;</span>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!empty($upgradeInfo['link'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('URL:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <a class="url" href="<?php echo $upgradeInfo['link']; ?>"><?php echo $upgradeInfo['link']; ?></a>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!empty($upgradeInfo['md5'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('MD5 hash:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <span class="md5"><?php echo $upgradeInfo['md5']; ?>&nbsp;</span>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!empty($upgradeInfo['changelog'])) : ?>
            <div style="clear:both;">
                <label class="label-small"><?php echo $this->l('Changelog:'); ?></label>
                <div class="margin-form margin-form-small" style="padding-top:5px">
                    <a class="changelog" href="<?php echo $upgradeInfo['changelog']; ?>"><?php echo $this->l('see changelog'); ?></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
