<?php
/**
 * 2007-2016 PrestaShop
 *
 * Thirty Bees is an extension to the PrestaShop e-commerce software developed by PrestaShop SA
 * Copyright (C) 2017 Thirty Bees
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    Thirty Bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017 Thirty Bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark & property of PrestaShop SA
 */

/** @var AdminThirtyBeesMigrateController $this */
$upgrader = \PsOneSixMigrator\Upgrader::getInstance();
?>
<div class="clearfix">
	<strong><?php echo $this->l('Going to migrate to thirty bees version'); ?>:</strong> <em id="selectedVersion"><?php echo $upgrader->version ?: $this->l('Nothing available'); ?></em>
</div>
<div class="form-group">
	<label for="channelSelect"><?php echo $this->l('Channel:'); ?></label>
	<select id="channelSelect" name="channel" class="form-control fixed-width-xxl">
		<?php foreach (['stable', 'rc', 'beta', 'alpha'] as $channel) : ?>
		<option id="use<?php echo ucfirst($channel); ?>" value="<?php echo $channel; ?>"><?php echo $channel; ?></option>
		<?php endforeach; ?>
	</select>
	<div id="channelSelectErrors" class="alert alert-danger" style="display:none"></div>
</div>
