<?php
/**
 * 2007-2016 PrestaShop
 *
 * Thirty Bees is an extension to the PrestaShop e-commerce software developed by PrestaShop SA
 * Copyright (C) 2017 Thirty Bees
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    Thirty Bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017 Thirty Bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark & property of PrestaShop SA
 */

/** @var AdminThirtyBeesMigrateController $this */

$currentPsConfig = $this->getcheckCurrentPsConfig();
$picOk = '<i class="icon icon-check" style="color: limegreen"></i>';
$picNok = '<i class="icon icon-times" style="color: firebrick">';
$picWarn = '<i class="icon icon-checkmark" style="color: orange">';
$adminDir = trim(str_replace(_PS_ROOT_DIR_, '', _PS_ADMIN_DIR_), DIRECTORY_SEPARATOR);
$maxExecTime = ini_get('max_execution_time');
$tools = \PsOneSixMigrator\UpgraderTools::getInstance();
PsOneSixMigrator\ConfigurationTest::testDir($adminDir.DIRECTORY_SEPARATOR.$tools->autoupgradeDir, true, $report);
?>

<div class="panel col-lg-6" id="currentConfigurationBlock">
	<div class="panel-heading"><?php echo $this->l('The pre-Upgrade checklist'); ?></div>
    <?php if (!$this->configOk()) : ?>
		<div class="clear"><br></div><p class="warn"><?php echo $this->l('The checklist is not OK. You can only upgrade your shop once all indicators are green.'); ?></p>
    <?php endif; ?>

	<div id="currentConfiguration">
		<p><?php echo $this->l('Before starting the upgrade process, please make sure this checklist is all green.'); ?></p>
		<table class="table" cellpadding="0" cellspacing="0">
			<tr>
				<td><?php echo $this->l('Your store\'s root directory is writable (with appropriate permissions)'); ?></td>
				<td><?php echo($currentPsConfig['root_writable'] ? $picOk : $picNok.' '.$tools->root_writable_report); ?></td>
			</tr>
			<tr>
				<td><?php echo sprintf($this->l('Directory %s is writable (with appropriate permissions)'), $tools->autoupgradePath); ?></td>
				<td><?php echo($currentPsConfig['admin_au_writable'] ? $picOk : $picNok.' '.$report); ?></td>
			</tr>
			<tr>
				<td><?php echo $this->l('PHP\'s "allow_url_fopen" option is turned on, or cURL is installed'); ?></td>
				<td><?php echo(PsOneSixMigrator\ConfigurationTest::testFopen() ? $picOk : $picNok); ?></td>
			</tr>
			<tr>
				<td><?php echo $this->l('Your store is in maintenance mode').' '.(!$currentPsConfig['shop_deactivated'] ? '<br><form method="post" action="'.static::$currentIndex.'&token='.$this->token.'"><input type="submit" class="button" name="putUnderMaintenance" value="'.$this->l('Click here to put your shop under maintenance').'"></form>' : ''); ?></td>
				<td><?php echo($currentPsConfig['shop_deactivated'] ? $picOk : $picNok); ?></td>
			</tr>
			<tr>
				<td><?php echo $this->l('PrestaShop\'s caching features are disabled'); ?></td>
				<td><?php echo($currentPsConfig['cache_deactivated'] ? $picOk : $picNok); ?></td>
			</tr>
			<tr>
				<td><?php echo sprintf($this->l('PHP\'s max_execution_time setting has a high value or is disabled entirely (current value: %s)'), ($maxExecTime == 0 ? $this->l('unlimited') : sprintf($this->l('%s seconds'), $maxExecTime))); ?></td>
				<td><?php echo($maxExecTime == 0 ? $picOk : $picWarn); ?></td>
			</tr>
		</table>
		<div class="panel-footer"><strong><?php echo $this->l('Please also make sure you make a full manual backup of your files and database.'); ?></strong></div>
	</div>
</div>
