<?php /** @var AdminThirtyBeesMigrate $this */ ?>
<fieldset id="comparisonBlock">
	<legend><?php echo $this->l('Version comparison'); ?></legend>
	<b><?php echo $this->l('PrestaShop Original version'); ?>:</b><br/>
	<span id="checkPrestaShopFilesVersion">
		<img id="pleaseWait" src="<?php echo __PS_BASE_URI__; ?>img/loader.gif"/>
	</span>
	<br/>
	<b><?php echo $this->l('Differences between versions'); ?>:</b><br/>
	<span id="checkPrestaShopModifiedFiles">
		<img id="pleaseWait" src="<?php echo __PS_BASE_URI__; ?>img/loader.gif"/>
	</span>
</fieldset>
