<?php
/** @var AdminThirtyBeesMigrate $this*/

$currentPsConfig = $this->getcheckCurrentPsConfig();
$picOk = '<img src="../img/admin/enabled.gif" alt="ok"/>';
$picNok = '<img src="../img/admin/disabled.gif" alt="nok"/>';
$picWarn = '<img src="../img/admin/warning.gif" alt="warn"/>';
$adminDir = trim(str_replace($this->prodRootDir, '', $this->adminDir), DIRECTORY_SEPARATOR);
$maxExecTime = ini_get('max_execution_time');
$report = '';
PsOneSixMigrator\ConfigurationTest::test_dir($adminDir.DIRECTORY_SEPARATOR.$this->autoupgradeDir, true, $report);
?>

<fieldset id="currentConfigurationBlock" class="width autoupgrade" style="float: left; width: 60%; margin-left: 30px;">
    <legend><?php echo $this->l('The pre-Upgrade checklist'); ?></legend>
    <?php if (!$this->configOk()) : ?>
        <div class="clear"><br></div><p class="warn"><?php echo $this->l('The checklist is not OK. You can only upgrade your shop once all indicators are green.'); ?></p>
    <?php endif; ?>

    <div id="currentConfiguration">
        <p><?php echo $this->l('Before starting the upgrade process, please make sure this checklist is all green.'); ?></p>
        <table class="table" cellpadding="0" cellspacing="0">
            <tr>
                <td><?php echo sprintf($this->l('The 1-click upgrade module is up-to-date (your current version is v%s)'), $this->getModuleVersion()); ?>
                    <?php echo ($currentPsConfig['module_version_ok'] ? '' : '&nbsp;&nbsp;'.(version_compare(_PS_VERSION_, '1.5.3.0', '>') ? '<strong><a href="index.php?controller=AdminModules&amp;token='.Tools::getAdminTokenLite('AdminModules').'&update=autoupgrade">'.$this->l('Update').'</a></strong> - ' : '').'<strong><a class="_blank" href="http://addons.prestashop.com/en/administration-tools-prestashop-modules/5496-1-click-upgrade-autoupgrade.html">'.$this->l('Download').'</a><strong> '); ?>
                </td>
                <td><?php echo ($currentPsConfig['module_version_ok'] ? $picOk : $picNok); ?></td>
            </tr>
            <tr>
                <td><?php echo $this->l('Your store\'s root directory is writable (with appropriate CHMOD permissions)'); ?></td>
                <td><?php echo ($currentPsConfig['root_writable'] ? $picOk : $picNok.' '.$this->root_writable_report); ?></td>
            </tr>

            <?php if ($report) : ?>
                <tr>
                    <td><?php echo $this->l('The "/admin/autoupgrade" directory is writable (appropriate CHMOD permissions)'); ?></td>
                    <td><?php echo ($currentPsConfig['admin_au_writable'] ? $picOk : $picNok.' '.$report); ?></td>
                </tr>
            <?php endif; ?>

            <?php
            if (!$safeMode = @ini_get('safe_mode')) {
                $safeMode = '';
            }
            $safeMode = in_array(Tools::strtolower($safeMode), [1, 'on']);
            ?>

            <tr>
                <td><?php echo $this->l('PHP\'s "Safe mode" option is turned off'); ?></td>
                <td><?php echo (!$safeMode ? $picOk : $picWarn); ?></td>
            </tr>
            <tr>
                <td><?php echo $this->l('PHP\'s "allow_url_fopen" option is turned on, or cURL is installed'); ?></td>
                <td><?php echo ((PsOneSixMigrator\ConfigurationTest::test_fopen() || PsOneSixMigrator\ConfigurationTest::test_curl()) ? $picOk : $picNok); ?></td>
            </tr>
            <tr>
                <td><?php echo $this->l('Your store is in maintenance mode').' '.(!$currentPsConfig['shop_deactivated'] ? '<br><form method="post" action="'.$this->currentIndex.'&token='.$this->token.'"><input type="submit" class="button" name="putUnderMaintenance" value="'.$this->l('Click here to put your shop under maintenance').'"></form>' : ''); ?></td>
                <td><?php echo ($currentPsConfig['shop_deactivated'] ? $picOk : $picNok); ?></td>
            </tr>
            <tr>
                <td><?php echo $this->l('PrestaShop\'s caching features are disabled'); ?></td>
                <td><?php echo ($currentPsConfig['cache_deactivated'] ? $picOk : $picNok); ?></td>
            </tr>
            <tr>
                <td><?php echo sprintf($this->l('PHP\'s max_execution_time setting has a high value or is disabled entirely (current value: %s)'), ($maxExecTime == 0 ? $this->l('unlimited') : sprintf($this->l('%s seconds'), $maxExecTime))); ?></td>
                <td><?php echo ($maxExecTime == 0 ? $picOk : $picWarn); ?></td></tr>
        </table>
        <p><?php echo $this->l('Please also make sure you make a full manual backup of your files and database.'); ?></p>
    </div>
</fieldset>
