<?php
/**
 * Copyright (C) 2017-2019 thirty bees
 * Copyright (C) 2007-2016 PrestaShop SA
 *
 * thirty bees is an extension to the PrestaShop software by PrestaShop SA.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    thirty bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017-2019 thirty bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark of PrestaShop SA.
 */

/** @var AdminThirtyBeesMigrateController $this */
?>
<br class="clear"/>
<fieldset class="autoupgradeSteps">
	<legend><?php echo $this->l('Step'); ?></legend>
	<h4><?php echo $this->l('Upgrade steps') ?>:</h4>
	<div>
		<a id="download" class="upgradestep">download</a>
		<a id="unzip" class="upgradestep">unzip</a>
		<a id="removeSamples" class="upgradestep">removeSamples</a>
		<a id="backupFiles" class="upgradestep">backupFiles</a>
		<a id="backupDb" class="upgradestep">backupDb</a>
		<a id="upgradeFiles" class="upgradestep">upgradeFiles</a>
		<a id="upgradeDb" class="upgradestep">upgradeDb</a>
		<a id="upgradeModules" class="upgradestep">upgradeModules</a>
		<a id="cleanDatabase" class="upgradestep">cleanDb</a>
		<a id="upgradeComplete" class="upgradestep">upgradeComplete</a>
	</div>
</fieldset>
