<?php /** @var AdminThirtyBeesMigrate $this */ ?>
<br class="clear"/>
<fieldset class="autoupgradeSteps">
	<legend><?php echo $this->l('Step'); ?></legend>
	<h4><?php echo $this->l('Upgrade steps') ?>:</h4>
	<div>
		<a id="download" class="upgradestep">download</a>
		<a id="unzip" class="upgradestep">unzip</a>
		<a id="removeSamples" class="upgradestep">removeSamples</a>
		<a id="backupFiles" class="upgradestep">backupFiles</a>
		<a id="backupDb" class="upgradestep">backupDb</a>
		<a id="upgradeFiles" class="upgradestep">upgradeFiles</a>
		<a id="upgradeDb" class="upgradestep">upgradeDb</a>
		<a id="upgradeModules" class="upgradestep">upgradeModules</a>
		<a id="cleanDatabase" class="upgradestep">cleanDb</a>
		<a id="upgradeComplete" class="upgradestep">upgradeComplete</a>
	</div>
</fieldset>
