<?php
/**
 * 2007-2016 PrestaShop
 *
 * Thirty Bees is an extension to the PrestaShop e-commerce software developed by PrestaShop SA
 * Copyright (C) 2017 Thirty Bees
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    Thirty Bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017 Thirty Bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark & property of PrestaShop SA
 */
use PsOneSixMigrator\UpgraderTools;

/** @var AdminThirtyBeesMigrateController $this */
$tokenPreferences = Tools::getAdminTokenLite('AdminPreferences');
// relative admin dir
$adminDir = trim(str_replace(_PS_ROOT_DIR_, '', _PS_ADMIN_DIR_), DIRECTORY_SEPARATOR);
$installVersion = ' 1.0.1';
$ajaxProcessor = \PsOneSixMigrator\AjaxProcessor::getInstance();
?>
<script src="https://cdn.jsdelivr.net/sweetalert2/6.5.3/sweetalert2.min.js" integrity="sha256-mxvrozpI8ZhaD7mKlr0z1BLafn8YoTTJFobEo9wlCUM=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.5.3/sweetalert2.min.css" integrity="sha256-n3wlJfrvYrUl1vS7mEs17EWYDW8fpE6DQv95+EnpHoY=" crossorigin="anonymous">

<script type="text/javascript">
	window.upgrader = {};
	window.upgrader._PS_MODE_DEV_ = <?php echo (defined('_PS_DEV_MODE_') && _PS_DEV_MODE_) ? 'true' : 'false'; ?>;
	window.upgrader.PS_AUTOUP_BACKUP = <?php echo (UpgraderTools::getConfig(UpgraderTools::BACKUP)) ? 'true' : 'false' ?>;

	window.upgrader.txtError = [];
	window.upgrader.txtError[0] = '<?php echo $this->l('Required field'); ?>';
	window.upgrader.txtError[1] = '<?php echo $this->l('Too long!'); ?>';
	window.upgrader.txtError[2] = '<?php echo $this->l('Fields are different!'); ?>';
	window.upgrader.txtError[3] = '<?php echo $this->l('This email address is wrong!'); ?>';
	window.upgrader.txtError[4] = '<?php echo $this->l('Impossible to send the email!'); ?>';
	window.upgrader.txtError[5] = '<?php echo $this->l('Cannot create settings file, if /config/settings.inc.php exists, please give the public write permissions to this file, else please create a file named settings.inc.php in config directory.'); ?>';
	window.upgrader.txtError[6] = '<?php echo $this->l('Cannot write settings file, please create a file named settings.inc.php in the "config" directory.'); ?>';
	window.upgrader.txtError[7] = '<?php echo $this->l('Impossible to upload the file!'); ?>';
	window.upgrader.txtError[8] = '<?php echo $this->l('Data integrity is not valided. Hack attempt?'); ?>';
	window.upgrader.txtError[9] = '<?php echo $this->l('Impossible to read the content of a MySQL content file.'); ?>';
	window.upgrader.txtError[10] = '<?php echo $this->l('Cannot access a MySQL content file.'); ?>';
	window.upgrader.txtError[11] = '<?php echo $this->l('Error while inserting data in the database:'); ?>';
	window.upgrader.txtError[12] = '<?php echo $this->l('The password is incorrect (alphanumeric string at least 8 characters).'); ?>';
	window.upgrader.txtError[14] = '<?php echo $this->l('A PrestaShop database already exists, please drop it or change the prefix.'); ?>';
	window.upgrader.txtError[15] = '<?php echo $this->l('This is not a valid file name.'); ?>';
	window.upgrader.txtError[16] = '<?php echo $this->l('This is not a valid image file.'); ?>';
	window.upgrader.txtError[17] = '<?php echo $this->l('Error while creating the /config/settings.inc.php file.'); ?>';
	window.upgrader.txtError[18] = '<?php echo $this->l('Error:'); ?>';
	window.upgrader.txtError[19] = '<?php echo $this->l('This PrestaShop database already exists. Please revalidate your authentication information to the database.'); ?>';
	window.upgrader.txtError[22] = '<?php echo $this->l('An error occurred while resizing the picture.'); ?>';
	window.upgrader.txtError[23] = '<?php echo $this->l('Database connection is available!'); ?>';
	window.upgrader.txtError[24] = '<?php echo $this->l('Database Server is available but database is not found'); ?>';
	window.upgrader.txtError[25] = '<?php echo $this->l('Database Server is not found. Please verify the login, password and server fields.'); ?>';
	window.upgrader.txtError[26] = '<?php echo $this->l('An error occurred while sending email, please verify your parameters.'); ?>';
	window.upgrader.txtError[37] = '<?php echo $this->l('Impossible to write the image /img/logo.jpg. If this image already exists, please delete it.'); ?>';
	window.upgrader.txtError[38] = '<?php echo $this->l('The uploaded file exceeds the upload_max_filesize directive in php.ini'); ?>';
	window.upgrader.txtError[39] = '<?php echo $this->l('The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form'); ?>';
	window.upgrader.txtError[40] = '<?php echo $this->l('The uploaded file was only partially uploaded'); ?>';
	window.upgrader.txtError[41] = '<?php echo $this->l('No file was uploaded.'); ?>';
	window.upgrader.txtError[42] = '<?php echo $this->l('Missing a temporary folder'); ?>';
	window.upgrader.txtError[43] = '<?php echo $this->l('Failed to write file to disk'); ?>';
	window.upgrader.txtError[44] = '<?php echo $this->l('File upload stopped by extension'); ?>';
	window.upgrader.txtError[45] = '<?php echo $this->l('Cannot convert your database\'s data to utf-8.'); ?>';
	window.upgrader.txtError[46] = '<?php echo $this->l('Invalid shop name'); ?>';
	window.upgrader.txtError[47] = '<?php echo $this->l('Your firstname contains some invalid characters'); ?>';
	window.upgrader.txtError[48] = '<?php echo $this->l('Your lastname contains some invalid characters'); ?>';
	window.upgrader.txtError[49] = '<?php echo $this->l('Your database server does not support the utf-8 charset.'); ?>';
	window.upgrader.txtError[50] = '<?php echo $this->l('Your MySQL server does not support this engine, please use another one like MyISAM'); ?>';
	window.upgrader.txtError[51] = '<?php echo $this->l('The file /img/logo.jpg is not writable, please CHMOD 755 this file or CHMOD 777'); ?>';
	window.upgrader.txtError[52] = '<?php echo $this->l('Invalid catalog mode'); ?>';
	window.upgrader.txtError[999] = '<?php echo $this->l('No error code available'); ?>';
	//upgrader
	window.upgrader.txtError[27] = '<?php echo $this->l('This installer is too old.'); ?>';
	window.upgrader.txtError[28] = '<?php echo sprintf($this->l('You already have the %s version.'), $installVersion); ?>';
	window.upgrader.txtError[29] = '<?php echo $this->l('There is no older version. Did you delete or rename the config/settings.inc.php file?'); ?>';
	window.upgrader.txtError[30] = '<?php echo $this->l('The config/settings.inc.php file was not found. Did you delete or rename this file?'); ?>';
	window.upgrader.txtError[31] = '<?php echo $this->l('Cannot find the SQL upgrade files. Please verify that the /install/upgrade/sql folder is not empty.'); ?>';
	window.upgrader.txtError[32] = '<?php echo $this->l('No upgrade is possible.'); ?>';
	window.upgrader.txtError[33] = '<?php echo $this->l('Error while loading SQL upgrade file.'); ?>';
	window.upgrader.txtError[34] = '<?php echo $this->l('Error while inserting content into the database'); ?>';
	window.upgrader.txtError[35] = '<?php echo $this->l('Unfortunately,'); ?>';
	window.upgrader.txtError[36] = '<?php echo $this->l('SQL errors have occurred.'); ?>';
	window.upgrader.txtError[37] = '<?php echo $this->l('The config/defines.inc.php file was not found. Where did you move it?'); ?>';
	window.upgrader.txtError[38] = '<?php echo $this->l('An update is currently in progress... Click "{OK}" to abort.'); ?>';

	window.upgrader.firstTimeParams = <?php echo $ajaxProcessor->buildAjaxResult(); ?>;

    window.upgrader.upgradeTabFileExists = <?php echo (file_exists(_PS_ADMIN_DIR_.DIRECTORY_SEPARATOR.'autoupgrade'.DIRECTORY_SEPARATOR.'ajax-upgradetab.php')) ? 'true' : 'false'; ?>;
    window.upgrader.ajaxLocation = '<?php echo __PS_BASE_URI__.$adminDir.'/autoupgrade/ajax-upgradetab.php'; ?>';

    window.upgrader.dir = '<?php echo $adminDir; ?>';
    window.upgrader.token = '<?php echo $this->token; ?>';
    window.upgrader.tab = '<?php echo get_class($this); ?>';

    window.upgrader.channel = '<?php echo UpgraderTools::getConfig('channel'); ?>';

    window.upgrader.currentIndex = '<?php echo AdminThirtyBeesMigrateController::$currentIndex; ?>';
    window.upgrader.ajaxToken = '<?php echo $this->generateAjaxToken(); ?>';
</script>
