<?php
/** @var AdminThirtyBeesMigrate $this */
$lines = [
    $this->l('My pre-Upgrade checklist is all good'),
    $this->l('My files and database are backed up'),
    sprintf($this->l('I understand my current theme will not work with my %s shop'), $this->upgrader->version_num),
    sprintf($this->l('I am aware most of my modules will not be compatible with my %s shop'), $this->upgrader->version_num),
    $this->l('I understand I will no longer have my advanced stock management configuration and data'),
    $this->l('I will have to reconfigure my permissions'),
    $this->l('If I have a custom menu in my back office, I will no longer be able to use it'),
];
?>

<fieldset id="hideStep17-2" style="background: white; border: solid 3px #585A69; font-size: 1.2em; display:none; width: 50%; margin-left: 25%; margin-top: 50px; margin-bottom: 50px;">
    <h3>Are you ready? Please check all this, it\'s important for your shop:<h3>
            <ul style="list-style-type: none;">
                <?php foreach ($lines as $k => $line) : ?>
                <li>
                    <input type="checkbox" name="goToUpgrade[]" id="goToUpgrade-<?php echo $k; ?>" value="<?php echo $k; ?>">
                    <label style="font-size: 1em;" class="t" for="goToUpgrade-<?php echo $k; ?>"><?php echo $line; ?></label><br>
                </li>
                <?php endforeach; ?>
            </ul>
            <p class="clear" style="text-align: center;">
                <a href="" id="showStep17-abort" style="font-size: 0.9em; margin-right: 20px;" class="">Abort, I am not ready!</a>
                <a href="" id="upgradeNow17" style="margin-right: 20px;" class="button-autoupgrade17 upgradestep">
                    <?php echo sprintf($this->l('Switch to %s for good!'), $this->upgrader->version_num); ?>
                </a>
            </p>
</fieldset>
