<?php
/**
 * Copyright (C) 2017-2019 thirty bees
 * Copyright (C) 2007-2016 PrestaShop SA
 *
 * thirty bees is an extension to the PrestaShop software by PrestaShop SA.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    thirty bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017-2019 thirty bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark of PrestaShop SA.
 */

/** @var AdminThirtyBeesMigrateController $this */
?>
<div id="informationBlock" class="panel col-lg-6">
    <div class="panel-heading"><?php echo $this->l('Welcome!'); ?></div>
	<p><?php echo $this->l('With the thirty bees migration module you can easily migrate from PrestaShop 1.6 to thirty bees'); ?></p>
	<span style="color: red; font-weight: bold"><?php echo $this->l('Please always perform a full manual backup of your files and database before starting any upgrade or migration.'); ?></span>
    <p><?php echo $this->l('Double-check the integrity of your backup and that you can easily manually roll-back if necessary.'); ?></p>
    <p><?php echo $this->l('If you do not know how to proceed, ask your hosting provider.'); ?></p>
</div>
